// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBKQ_rbbPlJycMSdTq3ixyV5rbV_-Mg4',
    appId: '1:684598632679:web:6e94a3b723ce0f2a178242',
    messagingSenderId: '684598632679',
    projectId: 'insatagram-c7269',
    authDomain: 'insatagram-c7269.firebaseapp.com',
    storageBucket: 'insatagram-c7269.appspot.com',
    measurementId: 'G-7D5W0FYHT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhoSyDfSgTmyXRMhMvO6MJCfFyewWA3E',
    appId: '1:684598632679:android:5e5fddbc32a4bc21178242',
    messagingSenderId: '684598632679',
    projectId: 'insatagram-c7269',
    storageBucket: 'insatagram-c7269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4B3PohanajImtUagPGFDTMivbOfpoI6A',
    appId: '1:684598632679:ios:bc11e6c0ff5f86a9178242',
    messagingSenderId: '684598632679',
    projectId: 'insatagram-c7269',
    storageBucket: 'insatagram-c7269.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4B3PohanajImtUagPGFDTMivbOfpoI6A',
    appId: '1:684598632679:ios:64fa422189c9243e178242',
    messagingSenderId: '684598632679',
    projectId: 'insatagram-c7269',
    storageBucket: 'insatagram-c7269.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
